### ISSUE TITLE
Marriage Allowance 

### ISSUE THREAD

**Issue by heythisiskishore** [hmrc/marriage-allowance-des-stub#30]

**Comment by heythisiskishore** [comment]
Hi,
When we are  trying Marriage Allowance API  we are getting ERROR 
The error shows below :+1: 
{
    "code": "NOT_FOUND",
    "message": "Resource was not found"
}
Is this Marriage Allowance endpoint is showing in live?

We have received a mail from SDS Team regarding Marriage Allowance API  for the version v2.0.
Is this available Now in Sandbox and Production?

Thank You.

**Comment by frikit** [comment]
Duplicate of https://github.com/hmrc/marriage-allowance-des-stub/issues/31
